name: "Complaince as Code pipeline"

on:
  push: 
    branches: [main, stage]
    paths:
      - infra/**
      - infra_eks/**
      - policy/**
      - .github/workflows/compliance.yml
  pull_request:
    branches: [main, stage]
    paths:
      - infra/**
      - infras_eks/**
      - policy/**
      - .github/workflows/compliance.yml
  workflow_dispatch:

jobs:
  terraform-compliance:
    name: "Terraform compliance"
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: TF init
        id: init
        run: terraform -chdir=infra init -backend=false

      - name: TF format
        id: fmt
        run: terraform -chdir=infra fmt -check -recursive

      - name: TF validate
        id: validate
        run: terraform -chdir=infra validate

      - name: tfsec scan
        uses: aquasecurity/tfsec-action@b466648d6e39e7c75324f25d83891162a721f2d6
        with:
          working_directory: infra

      - name: Checkov scan
        id: checkov
        uses: bridgecrewio/checkov-action@99bb2caf247dfd9f03cf984373bc6043d4e32ebf
        with:
          directory: infra
          quiet: true
          soft_fail: false

      - name: Terraform plan for policy evaluation
        run: |
          terraform -chdir=infra plan \
            -var="project_name=skillnest" \
            -var="db_url=dummy" \
            -var="db_username=dummy" \
            -var="db_password=dummy" \
            -var="jwt_secret=dummy" \
            -var='cors_allowed_origins=["http://localhost:3000"]' \
            -var="cloudinary_cloud_name=dummy" \
            -var="cloudinary_api_key=dummy" \
            -var="cloudinary_api_secret=dummy" \
            -input=false \
            -out=tfplan.binary

      - name: Export plan json
        run: terraform -chdir=infra show -json tfplan.binary > tfplan.json

      - name: Setup Conftest
        uses: instrumenta/conftest-action@2b17b6e48009573bfee75b6f2b51bb1dacb05a2a


      - name: OPA policy check
        run: conftest test tfplan.json -p policy/terraform



